name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: Modern-YT-Downloader
            asset_name: Modern-YT-Downloader-Linux
          - os: windows-latest
            artifact_name: Modern-YT-Downloader.exe
            asset_name: Modern-YT-Downloader-Win.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Build with PyInstaller (Using Spec File)
        # Menggunakan build.spec agar aset CustomTkinter terbawa
        run: uv run pyinstaller build.spec --clean

      - name: Rename artifact for identification
        shell: bash
        run: |
          mv dist/${{ matrix.artifact_name }} dist/${{ matrix.asset_name }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}